fixes:
  - "ballerina/http/**/::../ballerina/"
  - "io/ballerina/stdlib/http/compiler/::./compiler-plugin/src/main/java/io/ballerina/stdlib/http/compiler/"

ignore:
  - "ballerina-tests"
  - "native/src/main/java/io/ballerina/stdlib/http/api/testutils"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
