[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.6"

[[dependency]]
org = "ballerina"
name = "cache"
version = "2.0.6"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.6.4"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.0.6"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "1.0.8"

[[dependency]]
org = "ballerina"
name = "oauth2"
version = "1.0.6"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.0.6"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.0.6"

[[dependency]]
org = "ballerina"
name = "time"
version = "1.0.7"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.0.6"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.6.1"

[[dependency]]
org = "ballerina"
name = "reflect"
version = "0.5.6"
