[package]
org = "ballerina"
name = "http_tests"
version = "1.0.2"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.2"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.6.0"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.0.2"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.0.2"

[[dependency]]
org = "ballerina"
name = "runtime"
version = "0.5.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.0.2"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "0.5.2"

[[platform.java11.dependency]]
path = "../http-native/build/libs/http-native-1.0.2-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "http"
version = "1.0.2-SNAPSHOT"
